from neurones import *
from random import *

neuroneCouche1Numero1 = Neurone()
neuroneCouche1Numero2 = Neurone()
neuroneCouche1Numero3 = Neurone()
neuroneCouche1Numero4 = Neurone()
neuroneCouche1Numero5 = Neurone()
neuroneCouche1Numero6 = Neurone()
neuroneCouche1Numero7 = Neurone()
neuroneCouche1Numero8 = Neurone()
neuroneCouche1Numero9 = Neurone()
neuroneCouche1Numero10 = Neurone()
neuroneCouche1Numero11 = Neurone()
neuroneCouche1Numero12 = Neurone()
neuroneCouche1Numero13 = Neurone()

neuroneCouche2Numero1 = Neurone()
neuroneCouche2Numero2 = Neurone()
neuroneCouche2Numero3 = Neurone()
neuroneCouche2Numero4 = Neurone()
neuroneCouche2Numero5 = Neurone()
neuroneCouche2Numero6 = Neurone()
neuroneCouche2Numero7 = Neurone()
neuroneCouche2Numero8 = Neurone()
neuroneCouche2Numero9 = Neurone()
neuroneCouche2Numero10 = Neurone()
neuroneCouche2Numero11 = Neurone()
neuroneCouche2Numero12 = Neurone()
neuroneCouche2Numero13 = Neurone()
